### ISSUE TITLE
ESPCAM32 Webcam Server - Flash

### ISSUE THREAD

**Issue by r4gm** [PalomaVilchis/ESP32_CAM_G4#1]
![Screen Shot 2021-09-18 at 11 08 42](https://user-images.githubusercontent.com/17714668/133895434-6c8a37ef-15fc-4ffc-9c9e-fe06aa0f3a6c.png)
![Screen Shot 2021-09-18 at 11 09 02](https://user-images.githubusercontent.com/17714668/133895435-4ec486d3-86a6-41d7-bdee-0480f0de0a5e.png)
![Screen Shot 2021-09-18 at 11 10 09](https://user-images.githubusercontent.com/17714668/133895436-ff97de2a-aeb6-4f72-aef4-9742910e377a.png)

[https://drive.google.com/drive/folders/117OzqXVHpQPvFfKgLVFyP40bLvTmhjAx?usp=sharing](Drive)

**Comment by PalomaVilchis** [comment]
:)
