### ISSUE TITLE
Video de flash

### ISSUE THREAD

**Issue by CesarWyky** [PalomaVilchis/ESP32_CAM_G4#10]
https://photos.google.com/share/AF1QipOi7ORn8d0fHF1E43OLyiU99ApJm-xJAkANl4pC_pulQ9_CZUVFrde5BEHP0xxMhA?key=WDlBd0NwSVpDWGhUcTh4ODNOYURUMnc0WWw0V3Bn

**Comment by PalomaVilchis** [comment]
:)
