### ISSUE TITLE
ESPCAM con FLASH

### ISSUE THREAD

**Issue by AlejandroSalinasV** [PalomaVilchis/ESP32_CAM_G4#11]
Este son los resultados obtenidos. 
<img width="1280" alt="Captura de pantalla (2425)" src="https://user-images.githubusercontent.com/87546710/133896819-8d56ebe0-bfad-495d-87fc-fefedb56aa10.png">
![image](https://user-images.githubusercontent.com/87546710/133896903-943fad97-ab4a-4986-902b-88fd62f0b4ae.png)

Video: 
https://drive.google.com/file/d/1X89cAGYZZ8uppBS_1oITEqAKd49x-dxF/view?usp=sharing
Nota: Casi me quedo ciego con flash :'v :'v. 
Salu2.

**Comment by PalomaVilchis** [comment]
jajaja si les dije en clase que cuidado con el flash. :)
