### ISSUE TITLE
ESP32CAM Camara y flash - Iván Córdova

### ISSUE THREAD

**Issue by ivanCordova777** [PalomaVilchis/ESP32_CAM_G4#12]
Prueba de cámara con flash

Flash apagado:
![psy_off_enviar](https://user-images.githubusercontent.com/87504488/133897854-67f0a194-f051-4874-a46d-2df71a695cbc.png)

Flash encendido:
![psy_on_enviar](https://user-images.githubusercontent.com/87504488/133897889-b6f04fdd-98c0-41b5-99ae-060c94fbc1cb.png)

**Comment by PalomaVilchis** [comment]
:)
