### ISSUE TITLE
Videos ESP32-CAM

### ISSUE THREAD

**Issue by cjalpa** [PalomaVilchis/ESP32_CAM_G4#13]
https://drive.google.com/file/d/1DpM4yP4zRQugWXLWU_OxlRnPjNs2IGSI/view?usp=sharing
https://drive.google.com/file/d/1Dvwya971usaTkn8JfoXu2ZEUW68nyHyu/view?usp=sharing

**Comment by PalomaVilchis** [comment]
:)
