### ISSUE TITLE
Prueba de funcionamiento Mario A. Ramírez

### ISSUE THREAD

**Issue by mramirezr** [PalomaVilchis/ESP32_CAM_G4#2]
Esp32cam funcionado con mqtt y activación de flash remota.

![WhatsApp Image 2021-09-09 at 9 20 01 PM](https://user-images.githubusercontent.com/87407403/133895817-39d9d71e-e6c6-49e3-98a0-b67c50b9092f.jpeg)
![WhatsApp Image 2021-09-09 at 9 20 00 PM](https://user-images.githubusercontent.com/87407403/133895818-579e2662-885f-4609-9617-a997b3c657ac.jpeg)

**Comment by PalomaVilchis** [comment]
:)
