### ISSUE TITLE
WebCamServer_Jonathan_Ramirez

### ISSUE THREAD

**Issue by JonathanR02** [PalomaVilchis/ESP32_CAM_G4#21]
![20210921204811](https://user-images.githubusercontent.com/87575799/134271350-54340932-79d8-498b-8911-89bc31f6defa.jpg)
![WhatsApp Image 2021-09-21 at 8 54 00 PM](https://user-images.githubusercontent.com/87575799/134271353-1ee28dcd-fe28-4874-9eb0-d83e7699b16d.jpeg)
![WhatsApp Image 2021-09-21 at 8 54 00 PM (1)](https://user-images.githubusercontent.com/87575799/134271362-0e5f5c4b-1457-419c-b639-bb8d2f4ed04e.jpeg)

![WhatsApp Image 2021-09-21 at 8 54 01 PM](https://user-images.githubusercontent.com/87575799/134271370-76ce8014-bcba-4d54-9886-9c2a9dd709cd.jpeg)
![WhatsApp Image 2021-09-21 at 8 54 02 PM](https://user-images.githubusercontent.com/87575799/134271383-9000c67f-8534-4dd5-9274-7d9f74bf66cf.jpeg)

**Comment by PalomaVilchis** [comment]
:)
