### ISSUE TITLE
ESP32 Cámara + Flash

### ISSUE THREAD

**Issue by luisPerez19** [PalomaVilchis/ESP32_CAM_G4#24]
Enlace del drive (video):
https://drive.google.com/drive/folders/1EFV00nfCFryxOAxK0eSwRUtl04Evpi4t?usp=sharing

Nota: soy el issue de blackzero777 (pero ya lo cerré), tengo dos cuentas y me equivoque este es el bueno, una disculpa.

![image](https://user-images.githubusercontent.com/87548725/134288737-fe684c94-6b4f-42a2-b39d-d5d702281dc5.png)

![image](https://user-images.githubusercontent.com/87548725/134288989-8bf57f59-c13c-4e3e-ad46-8fafb3f1325f.png)

**Comment by PalomaVilchis** [comment]
no te preocupes.. ¡Mario! :)
