### ISSUE TITLE
ESP32CAM Joselyn Martinez

### ISSUE THREAD

**Issue by JoselynMaM14** [PalomaVilchis/ESP32_CAM_G4#5]
https://drive.google.com/drive/u/0/folders/1aSlN91uqkLl9ys2YLqc2wvuSKMNt11Sj

**Comment by PalomaVilchis** [comment]
No puedo ver las imágenes Joselyn

**Comment by JoselynMaM14** [comment]
https://drive.google.com/drive/folders/1aSlN91uqkLl9ys2YLqc2wvuSKMNt11Sj?usp=sharing
Me parece que con este link ya podrá acceder
