### ISSUE TITLE
ESP32CAM_FLASH_ARELI_ROJO

### ISSUE THREAD

**Issue by AreliRED** [PalomaVilchis/ESP32_CAM_G4#9]
https://correocuauammx-my.sharepoint.com/:f:/g/personal/arojoh_correo_cua_uam_mx/Evd2yCELC0xEuPkrSBmRiygBgaB_KKMLfkFnHrKOtdDZ7Q?e=izoZmD

**Comment by PalomaVilchis** [comment]
las pecositas... :)
